FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Rendering.bf"]

[MainWindow]
X = 373
Y = 56
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 200.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Rendering.bf"
TabWidth = 105.0
Type = "SourceViewPanel"
FilePath = "src\\Rendering.bf"
CursorPos = 8041
VertPos = 5263.0
ProjectName = "FractelOPOP"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 260.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5258621
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 87.0
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 360.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 338.0}, {Width = 346.0}, {Width = 216.0}]
Items = ["0x26F'49B859A0", "0x275'95785980", "fc.lastRenderingTime", "timerLabels[0].mStringPointer", "timerLabels[1].mStringPointer", "timerLabels[2].mStringPointer", "fc.LastRenderingTimes[0]", "lImages", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 216.0}, {Width = 726.0}, {Width = 216.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4741379
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[Breakpoints]]
File = "src\\Entity\\FractelChunk.bf"
Line = 112
Column = 4

[[Breakpoints]]
File = "c:\\Program Files\\BeefLang\\BeefLibs\\SDL2\\src\\SDLApp.bf"
Line = 20
Column = 5

[[Breakpoints]]
File = "src\\Entity\\FractelChunkMultiThread.bf"
Line = 265
Column = 4

[[Breakpoints]]
File = "c:\\Program Files\\BeefLang\\Projects\\BasicEngine\\src\\Rendering\\DrawUtils.bf"
Line = 157
Column = 4

[[Breakpoints]]
File = "c:\\Program Files\\BeefLang\\Projects\\BasicEngine\\src\\Rendering\\DrawUtils.bf"
Line = 151
Column = 4

[[Breakpoints]]
File = "src\\Entity\\FractelChunkMultiThread.bf"
Line = 242
Column = 4

[[Breakpoints]]
File = "src\\Entity\\FractelChunkMultiThread.bf"
Line = 71
Column = 5

[[Breakpoints]]
File = "src\\Entity\\FractelChunkMultiThread.bf"
Line = 262
Column = 4

[[Breakpoints]]
File = "c:\\Program Files\\BeefLang\\BeefLibs\\SDL2\\src\\SDLApp.bf"
Line = 182
Column = 4

[[Breakpoints]]
File = "src\\Entity\\FractelChunkMultiThread.bf"
Line = 116
Column = 4
